language: ruby

rvm:
  - 2.4.0
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - jruby-18mode
  - jruby-19mode
  - ruby-head
  - 1.8.7
  - ree

before_install:
  - gem install bundler

script: "ruby ./test/test_all.rb"

branches:
  only:
    - build
    - cover-check
